version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/admin"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/api"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/api"
    target-branch: "dev"
    schedule:
      interval: "daily"
